### ISSUE TITLE
apk

### ISSUE THREAD

**Issue by OllO18** [Berdsen/telekom-sport-android-tv-unofficial#8]
Thanks a lot for your work.
Using your app for 10 month with no problems.
Now i can´t connect to replays and live content.
Wanted to update now to newest version.
But shame on me i´m to stupied to find the apk.
Am i blind?
Sry to bother you.
Oliver

**Comment by Berdsen** [comment]
Hi  @OllO18,

no problem :)

The Telekom has changed the Login Url, so I had to update the sources.

You can always find the new releases here: https://github.com/Berdsen/telekom-sport-android-tv-unofficial/releases and also on the main page, when you click the release button:

![image](https://user-images.githubusercontent.com/2563949/65871508-d9bdf480-e37e-11e9-95e8-a2df976f12c2.png)

Furthermore I had some problems during installation, because my Phillips Tv had turned on App Scanning for untrusted apps. It claimed, that the author of this app (me :) ) is not known and so the install didn't work. I had to turn this off in the tv settings and after the installation turned this on again. But perhaps you don't have that issue.

If you found and installed the new version, you can close this issue or post mroe questions here :)

Berdsen

**Comment by OllO18** [comment]
thanks a lot. Works fine again!
